ALTER TABLE AnalyzedECG NOCHECK CONSTRAINT ALL;
ALTER TABLE ECG NOCHECK CONSTRAINT ALL;
ALTER TABLE ECGMonitor NOCHECK CONSTRAINT ALL;
ALTER TABLE Patient NOCHECK CONSTRAINT ALL;
UPDATE AnalyzedECG SET MonitorID = '1' WHERE MonitorID='Måler1';
UPDATE ECG SET MonitorID = '1' WHERE MonitorID='Måler1';
UPDATE ECGMonitor SET ECGMonitorID = '1' WHERE ECGMonitorID='Måler1';
UPDATE Patient SET LinkedECG = '1' WHERE LinkedECG='Måler1';

UPDATE AnalyzedECG SET MonitorID = '2' WHERE MonitorID='Måler2';
UPDATE ECG SET MonitorID = '2' WHERE MonitorID='Måler2';
UPDATE ECGMonitor SET ECGMonitorID = '2' WHERE ECGMonitorID='Måler2';
UPDATE Patient SET LinkedECG = '2' WHERE LinkedECG='Måler2';

ALTER TABLE AnalyzedECG CHECK CONSTRAINT ALL;
ALTER TABLE ECG CHECK CONSTRAINT ALL;
ALTER TABLE ECGMonitor CHECK CONSTRAINT ALL;
ALTER TABLE Patient CHECK CONSTRAINT ALL;